name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer les dépendances avec npm install
      - name: Install dependencies
        run: npm install

      # Lancer le build avec npm ci après installation
      - name: Run npm ci
        run: npm ci

      # Compiler l'application Angular
      - name: Build Angular project
        run: npm run build
